name: Upload Images to AWS S3

on:
  push:
    branches:
      - main
    paths:
      - 'Assets/Multiplayer/Thumbs/thumb*.png'


jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload images to S3
        run: |
          aws s3 sync ./Assets/Multiplayer/Thumbs s3://teste-thumb-matheus-silva/ --size-only \
            --exclude "*" \
            --include "thumb-*.png"
        
            
